### ISSUE TITLE
Partition rechunks output along non-parallelized dims

### ISSUE THREAD

**Issue by nbren12** [spencerkclark/xpartition#8]
Partition._initialize_store changes the chunking along dimensions that are not
parallelized over (`dims`). This leads to problems when writing to remote zarr
stores, when dask tries to write many smaller chunks to a single chunk in the
output. Google cloud storage only allows 1 update/second to a given object, so
this very quickly results in API request errors.

**Comment by spencerkclark** [comment]
I think what I have in #9 should address this.  I tried to go for what I think is the simplest approach for now.  Let me know how you feel about it.
